# Databricks notebook source
# DBTITLE 1,NotebookLM + Google Cloud TTS Integration
# MAGIC %md
# MAGIC ---
# MAGIC ## 🎙️ Phase 2: Automated Audio Generation
# MAGIC
# MAGIC **Three podcast types, fully automated:**
# MAGIC
# MAGIC | Type | Source | Frequency | Duration |
# MAGIC |------|--------|-----------|----------|
# MAGIC | Daily CA Podcast | Today's stories + traps + modes | Daily 8:30 AM | 15-20 min |
# MAGIC | Strategic Topic Deep-Dive | Mastery tracker weak topics | 2x/week | 20-30 min |
# MAGIC | Quick Revision Brief | Key insights + flashcards | Daily | 5 min |
# MAGIC
# MAGIC **Two audio engines:**
# MAGIC - **NotebookLM** (via `notebooklm-py`) — best quality, AI hosts, free
# MAGIC - **Google Cloud TTS** (WaveNet) — reliable fallback, $406 credits
# MAGIC
# MAGIC ---

# COMMAND ----------

# DBTITLE 1,Cell 1: Configuration & Setup
# ═══════════════════════════════════════════════════════════════════════════
# NB8: AUDIO GENERATOR — UPSC PODCAST PIPELINE
# ═══════════════════════════════════════════════════════════════════════════
# Reads NB7 outputs + Delta tables → Podcast transcript + Key insights
# Scheduled daily at 8:30 AM IST (after NB7 completes at 8:00 AM)
# ═══════════════════════════════════════════════════════════════════════════

from datetime import date, datetime
import json, os, re, textwrap

# ── Configuration ──────────────────────────────────────────────────────────
TODAY = date.today().isoformat()  # e.g., 2026-03-30
MODEL = "databricks-claude-sonnet-4"

# Paths
BASE_DIR       = "/Volumes/upsc_catalog/rag/obsidian_ca"
PRACTICE_DIR   = f"{BASE_DIR}/Daily_Practice/{TODAY}"
OBSIDIAN_CA    = f"{BASE_DIR}/UPSC_2026/01_Current_Affairs/2026"

# Mode file names (written by NB7 export cell)
MODE_FILES = {
    1: "01_Knowledge_QA.md",
    2: "02_KARL_Evaluation.md",
    3: "03_Prelims_MCQs.md",
    4: "04_Ethics_Case_Study.md",
    5: "05_Mains_Model_Answers.md",
    6: "06_Telugu_Optional.md",
    7: "07_AI_Tutor_Brief.md",
    8: "08_Phone_Summary.md",
}

# Output files (generated by this notebook)
OUTPUT_FILES = {
    "combined":   f"{PRACTICE_DIR}/combined_for_podcast.md",
    "transcript": f"{PRACTICE_DIR}/podcast_transcript.md",
    "insights":   f"{PRACTICE_DIR}/key_insights.md",
    "daily_note": f"{PRACTICE_DIR}/Daily_Note.md",
}

# ── Helpers ────────────────────────────────────────────────────────────────
def safe_write(path, content):
    """Write content to Volume path, return (success, size)."""
    try:
        dbutils.fs.put(path, content, overwrite=True)
        size = len(content.encode('utf-8'))
        return True, size
    except Exception as e:
        print(f"   ❌ Write failed {path}: {e}")
        return False, 0

def safe_read(path):
    """Read text from Volume path, return content or None."""
    try:
        return dbutils.fs.head(path, 65536)  # 64 KB max per file
    except Exception:
        return None

def escape_sql(text):
    """Escape text for embedding in SQL string literals."""
    return text.replace("'", "''")

# ── Verify prerequisites ──────────────────────────────────────────────────
print(f"🎙️  NB8 Audio Generator — {TODAY}")
print(f"{'='*60}")

# Check if NB6 data exists for today
story_count = spark.sql(f"""
    SELECT COUNT(*) AS n FROM upsc_catalog.rag.stories
    WHERE date = '{TODAY}'
""").collect()[0]['n']

print(f"   Stories in Delta for today: {story_count}")
if story_count == 0:
    print("   ⚠️  No stories found — NB6 may not have run yet.")
    print("   Pipeline will use fallback content if available.")

# Check if Daily_Practice directory exists
try:
    dbutils.fs.mkdirs(PRACTICE_DIR)
    print(f"   Output dir: {PRACTICE_DIR} ✓")
except Exception as e:
    print(f"   ⚠️  Could not create dir: {e}")

print(f"   Model: {MODEL}")
print(f"{'='*60}")

# COMMAND ----------

# DBTITLE 1,Cell 2: Load All Content (Delta + Exported Files)
# ═══════════════════════════════════════════════════════════════════════════
# CELL 2: Load all content — Delta tables + NB7 exported markdown files
# ═══════════════════════════════════════════════════════════════════════════

print(f"📂 Loading content for {TODAY}...")
print(f"{'-'*50}")

# ── 1. Load from Delta tables (primary source — always available) ────────
stories_df = spark.sql(f"""
    SELECT s.title, s.priority, s.gs_papers, s.topic_cluster,
           s.keywords, s.slug,
           d.pyq_patterns, d.mains_skeleton, d.static_links
    FROM upsc_catalog.rag.stories s
    LEFT JOIN upsc_catalog.rag.deep_analysis d
        ON d.story_id = s.story_id AND d.date = s.date
    WHERE s.date = '{TODAY}'
    ORDER BY CASE s.priority
        WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2
        WHEN 'MEDIUM' THEN 3 ELSE 4 END
""").collect()

traps_df = spark.sql(f"""
    SELECT trap_type, wrong_belief, correct_belief, severity, story_slug
    FROM upsc_catalog.rag.story_traps
    WHERE created_date = '{TODAY}'
    ORDER BY CASE severity WHEN 'HIGH' THEN 1 WHEN 'MEDIUM' THEN 2 ELSE 3 END
""").collect()

geo_df = spark.sql(f"""
    SELECT g.story_id, g.location_name, g.strategic_importance
    FROM upsc_catalog.rag.geography_context g
    WHERE g.date = '{TODAY}'
""").collect()

print(f"   Delta: {len(stories_df)} stories, {len(traps_df)} traps, {len(geo_df)} geo entries")

# ── 2. Load NB7 exported markdown files (secondary — may not exist yet) ──
mode_contents = {}
for mode_num, filename in MODE_FILES.items():
    filepath = f"{PRACTICE_DIR}/{filename}"
    content = safe_read(filepath)
    if content:
        mode_contents[mode_num] = content
        print(f"   Mode {mode_num}: ✅ {filename} ({len(content):,} chars)")
    else:
        print(f"   Mode {mode_num}: ⬜ {filename} (not exported yet)")

# ── 3. Load from daily_practice_queue if available ───────────────────────
queue_row = None
try:
    queue_rows = spark.sql(f"""
        SELECT * FROM upsc_catalog.rag.daily_practice_queue
        WHERE ca_date = '{TODAY}'
        ORDER BY queue_id DESC
        LIMIT 1
    """).collect()
    if queue_rows:
        queue_row = queue_rows[0]
        print(f"   Queue: ✅ Found entry {queue_row['queue_id']}")
except Exception:
    print(f"   Queue: ⬜ Table not available")

# ── 4. Build unified story context string ────────────────────────────────
def parse_gs(raw):
    try:
        return ", ".join(json.loads(raw)) if raw else "N/A"
    except Exception:
        return str(raw).replace('"', '').replace("[", "").replace("]", "")

story_context_lines = []
for s in stories_df:
    line = f"[{s.priority}] {s.title}\n"
    line += f"  Papers: {parse_gs(s.gs_papers)} | Cluster: {s.topic_cluster}\n"
    if s.keywords:
        line += f"  Keywords: {s.keywords}\n"
    if s.pyq_patterns and s.pyq_patterns != '[]':
        line += f"  PYQ Patterns: {s.pyq_patterns}\n"
    if s.mains_skeleton and s.mains_skeleton != '{}':
        line += f"  Mains Skeleton: {s.mains_skeleton}\n"
    story_context_lines.append(line)

story_block = "\n".join(story_context_lines) if story_context_lines else "No stories available for today."

trap_block = "\n".join([
    f"⚠️ [{t.severity}] {t.trap_type}: {t.wrong_belief} → CORRECT: {t.correct_belief}"
    for t in traps_df[:12]
]) if traps_df else "No traps identified today."

geo_block = "\n".join([
    f"📍 {g.location_name}: {g.strategic_importance}"
    for g in geo_df[:8]
]) if geo_df else "No geography context today."

# ── 5. Build mode content block (from exports or queue) ─────────────────
mode_text_block = ""
for mode_num in sorted(MODE_FILES.keys()):
    mode_name = MODE_FILES[mode_num].replace('.md', '').replace('_', ' ')
    if mode_num in mode_contents:
        # Use exported markdown (best quality)
        mode_text_block += f"\n## {mode_name}\n{mode_contents[mode_num][:2000]}\n"
    elif queue_row:
        # Fallback: use queue data
        field_map = {
            1: 'mode1_practice_answer', 5: 'mode5_model_answer',
            7: 'mode7_tutor_brief', 8: 'mode8_phone_summary'
        }
        field = field_map.get(mode_num)
        if field and queue_row[field] and not queue_row[field].startswith('See Mode'):
            mode_text_block += f"\n## {mode_name}\n{queue_row[field][:2000]}\n"

print(f"\n{'='*50}")
print(f"📊 Content summary:")
print(f"   Story context: {len(story_block):,} chars")
print(f"   Trap context:  {len(trap_block):,} chars")
print(f"   Geo context:   {len(geo_block):,} chars")
print(f"   Mode exports:  {len(mode_text_block):,} chars")
print(f"   Modes loaded:  {sorted(mode_contents.keys()) if mode_contents else 'none'}")

# COMMAND ----------

# DBTITLE 1,Cell 3: Build Combined Podcast Document
# ═══════════════════════════════════════════════════════════════════════════
# CELL 3: Build combined document optimized for podcast generation
# ═══════════════════════════════════════════════════════════════════════════

print(f"📝 Building combined podcast document...")

# Truncate blocks to fit within Claude's context
max_story = 3000
max_traps = 1500
max_geo = 800
max_modes = 4000

combined_doc = f"""---
date: {TODAY}
type: podcast-source
pipeline: NB8_Audio_Generator
stories: {len(stories_df)}
traps: {len(traps_df)}
---

# UPSC Daily Current Affairs Podcast — Source Document
**Date:** {TODAY} | **Stories:** {len(stories_df)} | **Traps:** {len(traps_df)}

---

## Instructions for AI Podcast Hosts

You are two UPSC coaching experts creating an engaging audio podcast:

**Host 1 — "Arjun" (The Analyst):**
- Constitutional/legal frameworks, case laws, Article references
- Connects current affairs to Laxmikanth, Spectrum, Ramesh Singh
- Speaks with authority, cites specific provisions

**Host 2 — "Priya" (The Strategist):**
- Exam strategy, memory tricks, common mistakes
- Creates mnemonics, points out UPSC traps
- Speaks with warmth, uses relatable examples

**Conversation Style:**
- Natural, engaging dialogue (not lecture format)
- Use phrases like "you know what's interesting...", "here's a trick..."
- Emphasize key facts verbally: "now THIS is important for Prelims..."
- Create mnemonics for complex topics
- Point out UPSC traps explicitly
- Connect CA to static syllabus chapters
- Keep it exam-focused and encouraging
- Target duration: 15–20 minutes

---

## Today's Stories

{story_block[:max_story]}

---

## Key Traps to Avoid

{trap_block[:max_traps]}

---

## Geography Context

{geo_block[:max_geo]}

---

## Practice Material from NB7

{mode_text_block[:max_modes] if mode_text_block else '(Mode exports not yet available — podcast will be generated from Delta data above.)'}
"""

# Save combined document
ok, size = safe_write(OUTPUT_FILES["combined"], combined_doc)
if ok:
    print(f"   ✅ combined_for_podcast.md saved ({size:,} bytes)")
else:
    print(f"   ❌ Failed to save combined document")

print(f"   Document length: {len(combined_doc):,} chars")

# COMMAND ----------

# DBTITLE 1,Cell 4: Generate Podcast Transcript via Claude
# ═══════════════════════════════════════════════════════════════════════════
# CELL 4: Generate 2-host conversational podcast transcript
# Uses ai_query(claude-sonnet-4) to convert combined doc into dialogue
# ═══════════════════════════════════════════════════════════════════════════

print(f"🎙️  Generating podcast transcript...")
print(f"   This may take 30–60 seconds (Claude is writing dialogue)...")

# Truncate combined_doc to fit Claude's input window safely
# ~12K chars of source + prompt overhead stays well within limits
source_content = combined_doc[:12000]

podcast_prompt = f"""You are a podcast scriptwriter for a UPSC preparation audio show.

Convert the following current affairs material into a natural, engaging 2-host
conversation transcript. The hosts are:
- ARJUN: The constitutional/legal analyst (cites Articles, cases, committees)
- PRIYA: The exam strategist (mnemonics, traps, study tips)

SOURCE MATERIAL:
{source_content}

GENERATE A PODCAST TRANSCRIPT following these rules:

1. FORMAT each line as:
   ARJUN: [dialogue]
   PRIYA: [dialogue]

2. STRUCTURE:
   - [00:00] Opening — energetic greeting, today's date, story count
   - [02:00] Story 1 — most important CA story deep-dive
   - [06:00] Story 2 — second story with cross-subject connections
   - [10:00] Trap Alert — discuss the biggest exam traps today
   - [13:00] Quick-Fire Round — rapid facts, Article numbers, key names
   - [16:00] Study Plan — what to revise tonight from static syllabus
   - [18:00] Closing — motivational send-off, tomorrow's preview

3. STYLE:
   - Conversational, not lecture-like
   - Include natural reactions: "Oh interesting!", "Wait, really?"
   - Create at least 2 mnemonics for complex topics
   - Explicitly say Article numbers and case names (for audio clarity)
   - Flag traps: "UPSC loves to test this wrong belief..."
   - Include brief pauses: [pause] for emphasis
   - End each section with a 1-line takeaway

4. LENGTH: Approximately 2500–3500 words (15–20 min read-aloud)

Generate the complete transcript now."""

try:
    safe_prompt = escape_sql(podcast_prompt)
    transcript = spark.sql(f"""
        SELECT ai_query(
            '{MODEL}',
            '{safe_prompt}',
            modelParameters => named_struct('max_tokens', 4096, 'temperature', 0.4)
        ) AS transcript
    """).collect()[0]['transcript']

    # Save transcript
    transcript_header = f"""---
date: {TODAY}
type: podcast-transcript
hosts: Arjun, Priya
duration_estimate: 15-20 min
generated_by: NB8_Audio_Generator
---

# 🎙️ UPSC Daily CA Podcast — {TODAY}

> Auto-generated conversational transcript. Read aloud or use with TTS.

---

"""
    full_transcript = transcript_header + transcript
    ok, size = safe_write(OUTPUT_FILES["transcript"], full_transcript)

    if ok:
        print(f"   ✅ Podcast transcript saved ({size:,} bytes)")
    else:
        print(f"   ❌ Failed to save transcript")

    # Preview
    print(f"\n{'='*60}")
    print(f"TRANSCRIPT PREVIEW (first 1000 chars):")
    print(f"{'='*60}")
    print(transcript[:1000])
    if len(transcript) > 1000:
        print(f"\n... [{len(transcript) - 1000:,} more chars]")

except Exception as e:
    print(f"   ❌ Podcast generation failed: {e}")
    import traceback
    traceback.print_exc()
    transcript = None

# COMMAND ----------

# DBTITLE 1,Cell 5: Generate Key Insights Summary
# ═══════════════════════════════════════════════════════════════════════════
# CELL 5: Extract key insights for quick 5-min revision
# ═══════════════════════════════════════════════════════════════════════════

print(f"💡 Generating key insights summary...")

insights_source = combined_doc[:8000]  # Use combined doc as source

insights_prompt = f"""You are a UPSC revision expert. Analyze today's current affairs
material and extract the most exam-critical insights.

SOURCE:
{insights_source}

GENERATE A KEY INSIGHTS SUMMARY with these exact sections:

## 🎯 Top 5 Must-Remember Facts
(Article numbers, dates, names, figures — things that appear in Prelims)
1. [Fact] — Why it matters
2. ...

## ⚠️ Top 3 Exam Traps
(Common wrong beliefs UPSC tests)
1. TRAP: [wrong belief] → TRUTH: [correct fact]
2. ...

## 📚 Static Topics to Revise Tonight
(Specific textbook chapters/sections)
- Laxmikanth: [chapter]
- Spectrum: [section]
- Ramesh Singh: [chapter]
- Other: [if applicable]

## 🔗 Cross-Subject Connections
(How today's CA links across GS papers)
| Today's Topic | GS1 | GS2 | GS3 | GS4 | Essay |
|---|---|---|---|---|---|
| [topic] | [link] | [link] | [link] | [link] | [theme] |

## ⚡ Quick Revision Flashcards
(5 Q&A pairs for self-testing)
Q1: [question]
A1: [answer]
...

## 🧠 Memory Hooks
(Mnemonics and one-liners to remember key facts)
- [Topic]: [mnemonic]

Be specific, cite real Article numbers and case names. Every fact must be accurate."""

try:
    safe_prompt = escape_sql(insights_prompt)
    insights = spark.sql(f"""
        SELECT ai_query(
            '{MODEL}',
            '{safe_prompt}',
            modelParameters => named_struct('max_tokens', 2048, 'temperature', 0.15)
        ) AS insights
    """).collect()[0]['insights']

    insights_header = f"""---
date: {TODAY}
type: key-insights
duration: 5-min revision
generated_by: NB8_Audio_Generator
---

# 💡 Key Insights — {TODAY}

> 5-minute revision card. Review before sleep for best retention.

---

"""
    full_insights = insights_header + insights
    ok, size = safe_write(OUTPUT_FILES["insights"], full_insights)

    if ok:
        print(f"   ✅ Key insights saved ({size:,} bytes)")
    else:
        print(f"   ❌ Failed to save insights")

    # Preview
    print(f"\n{'='*60}")
    print(f"KEY INSIGHTS PREVIEW:")
    print(f"{'='*60}")
    print(insights[:1200])
    if len(insights) > 1200:
        print(f"\n... [{len(insights) - 1200:,} more chars]")

except Exception as e:
    print(f"   ❌ Insights generation failed: {e}")
    import traceback
    traceback.print_exc()
    insights = None

# COMMAND ----------

# DBTITLE 1,Cell 6: Create Obsidian-Friendly Daily Note
# ═══════════════════════════════════════════════════════════════════════════
# CELL 6: Create Obsidian-compatible Daily Note with wikilinks
# ═══════════════════════════════════════════════════════════════════════════

print(f"📓 Creating Obsidian Daily Note...")

# Build story list for the daily note
story_list = ""
for i, s in enumerate(stories_df, 1):
    emoji = "🔴" if s.priority == "CRITICAL" else "🟠" if s.priority == "HIGH" else "🟢"
    story_list += f"{i}. {emoji} **{s.title}** ({parse_gs(s.gs_papers)})\n"

# Build file links
mode_links = ""
for mode_num, filename in sorted(MODE_FILES.items()):
    status = "✅" if mode_num in mode_contents else "⬜"
    name = filename.replace('.md', '').replace('_', ' ')
    mode_links += f"- {status} [[{filename}|{name}]]\n"

# Transcript and insights status
transcript_status = f"✅ [[podcast_transcript.md|Podcast Transcript]] ({len(transcript):,} chars)" if transcript else "⬜ Podcast transcript not generated"
insights_status = f"✅ [[key_insights.md|Key Insights]] ({len(insights):,} chars)" if insights else "⬜ Key insights not generated"

daily_note = f"""---
date: {TODAY}
type: daily-practice-note
pipeline: NB6 → NB7 → NB8
stories: {len(stories_df)}
traps: {len(traps_df)}
tags:
  - upsc/daily
  - current-affairs/{TODAY}
---

# 📅 UPSC Daily Practice — {TODAY}

## 📰 Today's Stories ({len(stories_df)})

{story_list if story_list else 'No stories today — check NB6 orchestrator.'}

## 📚 Practice Modes (NB7)

{mode_links}

## 🎙️ Audio & Insights (NB8)

- {transcript_status}
- {insights_status}
- ✅ [[combined_for_podcast.md|Combined Source Document]]

## ✅ Daily Review Checklist

- [ ] Read Key Insights (5 min)
- [ ] Listen to / read Podcast Transcript (15–20 min)
- [ ] Review Prelims MCQs (Mode 3)
- [ ] Practice 1 Mains answer (Mode 5)
- [ ] Note traps in error log
- [ ] Revise static topics listed in insights

## ⚠️ Today's Top Traps

{trap_block[:600] if trap_block else 'No traps identified.'}

## 📍 Geography Context

{geo_block[:400] if geo_block else 'No geography context.'}

---

> Generated by NB8 Audio Pipeline at {datetime.now().strftime('%H:%M IST')}
> Pipeline: [[NB6 CA Orchestrator]] → [[NB7 Practice Generator]] → [[NB8 Audio Generator]]
"""

ok, size = safe_write(OUTPUT_FILES["daily_note"], daily_note)
if ok:
    print(f"   ✅ Daily_Note.md saved ({size:,} bytes)")
else:
    print(f"   ❌ Failed to save daily note")

# COMMAND ----------

# DBTITLE 1,Cell 7: Execution Summary Report
# ═══════════════════════════════════════════════════════════════════════════
# CELL 7: Execution summary report
# ═══════════════════════════════════════════════════════════════════════════

from datetime import datetime as _dt

print(f"")
print(f"╔{'='*68}╗")
print(f"║  NB8 AUDIO GENERATOR — EXECUTION SUMMARY{'':>27}║")
print(f"╠{'='*68}╣")

# Check all output files
files_report = []
total_bytes = 0
for label, path in OUTPUT_FILES.items():
    content = safe_read(path)
    if content:
        sz = len(content.encode('utf-8'))
        total_bytes += sz
        files_report.append((label, path.split('/')[-1], sz, "✅"))
    else:
        files_report.append((label, path.split('/')[-1], 0, "❌"))

# Also check mode export files
mode_file_count = 0
for mode_num, filename in MODE_FILES.items():
    if safe_read(f"{PRACTICE_DIR}/{filename}"):
        mode_file_count += 1

print(f"║  Date: {TODAY}{'':>{48 - len(TODAY)}}║")
print(f"║  Time: {_dt.now().strftime('%H:%M:%S IST')}{'':>43}║")
print(f"║  Stories: {len(stories_df)} | Traps: {len(traps_df)} | Geo: {len(geo_df)}{'':>30}║")
print(f"╠{'-'*68}╣")
print(f"║  {'Output':<20} {'File':<30} {'Size':>8} {'Status':>6} ║")
print(f"╠{'-'*68}╣")

for label, fname, sz, status in files_report:
    sz_str = f"{sz:,}B" if sz > 0 else "--"
    print(f"║  {label:<20} {fname:<30} {sz_str:>8} {status:>6} ║")

print(f"╠{'-'*68}╣")
print(f"║  NB7 Mode Exports: {mode_file_count}/{len(MODE_FILES)} files{'':>34}║")
print(f"║  Total output size: {total_bytes:,} bytes{'':>33}║")

# Estimate podcast duration (avg 150 words/min speaking rate)
if transcript:
    word_count = len(transcript.split())
    duration_min = round(word_count / 150, 1)
    print(f"║  Podcast: ~{word_count:,} words ≈ {duration_min} min{'':>30}║")

print(f"╠{'='*68}╣")
print(f"║  OUTPUT DIRECTORY:{'':>50}║")
print(f"║  {PRACTICE_DIR}{'':>{68 - len(PRACTICE_DIR) - 2}}║")
print(f"║{'':>68}║")
print(f"║  Obsidian sync: files appear in vault at next sync{'':>17}║")
print(f"║  Access: Open Daily_Note.md in Obsidian for full index{'':>14}║")
print(f"╚{'='*68}╝")

print(f"\n✅ NB8 pipeline complete!")

# COMMAND ----------

# DBTITLE 1,Cell 8: Generate Actual Audio (TTS)
# ═══════════════════════════════════════════════════════════════════════════
# CELL 8: Convert podcast transcript → actual MP3 audio
#
# Uses gTTS (Google Translate TTS) for IMMEDIATE use (no API key)
# For production: switch to Google Cloud TTS for WaveNet voices
# ═══════════════════════════════════════════════════════════════════════════

import re, io

print(f"🔊 Generating audio from podcast transcript...")
print(f"{'-'*60}")

# ── Step 1: Install gTTS (free, no API key needed) ─────────────
try:
    from gtts import gTTS
    print("   ✅ gTTS already installed")
except ImportError:
    import subprocess
    subprocess.check_call(["pip", "install", "gtts", "-q"])
    from gtts import gTTS
    print("   ✅ gTTS installed")

# ── Step 2: Parse transcript into clean text for TTS ────────────
if transcript:
    # Clean up markdown formatting for audio
    audio_text = transcript

    # Remove markdown artifacts
    audio_text = re.sub(r'^#{1,3}\s+', '', audio_text, flags=re.MULTILINE)  # headers
    audio_text = re.sub(r'\*\*(.+?)\*\*', r'\1', audio_text)  # bold
    audio_text = re.sub(r'\*(.+?)\*', r'\1', audio_text)  # italic
    audio_text = re.sub(r'---+', '', audio_text)  # horizontal rules
    audio_text = re.sub(r'\[.*?\]', '', audio_text)  # timestamp markers

    # Replace host names with spoken pauses
    audio_text = audio_text.replace('ARJUN:', '\n... Arjun says: ')
    audio_text = audio_text.replace('PRIYA:', '\n... Priya says: ')

    # Truncate for gTTS (max ~5000 chars per call, we'll chunk it)
    MAX_CHUNK = 4500
    chunks = []
    current = ""
    for sentence in audio_text.split('. '):
        if len(current) + len(sentence) < MAX_CHUNK:
            current += sentence + '. '
        else:
            if current.strip():
                chunks.append(current.strip())
            current = sentence + '. '
    if current.strip():
        chunks.append(current.strip())

    print(f"   Transcript: {len(audio_text):,} chars → {len(chunks)} audio chunks")

    # ── Step 3: Generate MP3 audio ──────────────────────────────────
    print(f"   ⏳ Generating audio (this takes 1–2 minutes)...")

    audio_path = f"{PRACTICE_DIR}/podcast_{TODAY}.mp3"
    temp_local = f"/tmp/podcast_{TODAY}.mp3"

    try:
        # Combine all chunks into single audio
        combined_audio = io.BytesIO()
        for i, chunk_text in enumerate(chunks):
            tts = gTTS(text=chunk_text, lang='en', slow=False, tld='co.in')  # Indian English
            tts.write_to_fp(combined_audio)
            if (i + 1) % 5 == 0:
                print(f"      Chunk {i+1}/{len(chunks)} done...")

        # Save to local temp, then copy to Volume
        with open(temp_local, 'wb') as f:
            f.write(combined_audio.getvalue())

        audio_size = len(combined_audio.getvalue())

        # Copy to Volume
        dbutils.fs.cp(f"file:{temp_local}", audio_path)

        # Estimate duration (~150 words/min, ~6 bytes/ms for MP3)
        word_count = len(audio_text.split())
        est_minutes = round(word_count / 150, 1)

        print(f"\n   ✅ Audio generated!")
        print(f"   📁 Path: {audio_path}")
        print(f"   📊 Size: {audio_size:,} bytes ({audio_size/1024/1024:.1f} MB)")
        print(f"   ⏱️  Est. duration: ~{est_minutes} minutes")
        print(f"   🌐 Format: MP3 (plays on any device)")

        # Also save to Obsidian CA folder for easy access
        obsidian_audio = f"{OBSIDIAN_VOL}/UPSC_2026/01_Current_Affairs/2026/podcast_{TODAY}.mp3"
        dbutils.fs.cp(f"file:{temp_local}", obsidian_audio)
        print(f"   📓 Obsidian: {obsidian_audio}")

        # Clean up
        os.remove(temp_local)

    except Exception as e:
        print(f"   ❌ Audio generation failed: {e}")
        import traceback
        traceback.print_exc()
        audio_size = 0
else:
    print("   ⚠️  No transcript available. Run Cell 4 first.")
    audio_size = 0

print(f"\n{'='*60}")
print(f"   💡 To upgrade audio quality:")
print(f"   • Google Cloud TTS (WaveNet): pip install google-cloud-texttospeech")
print(f"   • ElevenLabs: pip install elevenlabs (premium voices)")
print(f"   • NotebookLM: Upload combined_for_podcast.md (see Cell 9)")

# COMMAND ----------

# DBTITLE 1,Cell 9: NotebookLM + Google AI Integration
# ═══════════════════════════════════════════════════════════════════════════
# CELL 9: NotebookLM Integration — Upload sources for AI podcast
#
# Strategy: Push combined_for_podcast.md + key knowledge files
# to NotebookLM via Google Generative AI API
#
# NotebookLM generates the BEST audio podcasts — 2 AI hosts,
# natural conversation, professional quality
# ═══════════════════════════════════════════════════════════════════════════

print(f"🧠 NotebookLM + Google AI Integration")
print(f"{'='*60}")

# ──────────────────────────────────────────────────────────────────────
# OPTION A: NotebookLM API (via Google Generative AI)
# ──────────────────────────────────────────────────────────────────────
# NotebookLM uses Google's Gemini models internally.
# We can use the Gemini API to create a NotebookLM-style experience.

# Step 1: Set your Google AI API key
# Get one free at: https://aistudio.google.com/apikey
GOOGLE_API_KEY = None  # Set your key here or in secrets

try:
    GOOGLE_API_KEY = dbutils.secrets.get("upsc-bot-secrets", "google-ai-key")
    print(f"   ✅ Google AI API key loaded from secrets")
except Exception:
    print(f"   ⚠️  Google AI API key not set.")
    print(f"   🔑 Get FREE key: https://aistudio.google.com/apikey")
    print(f'   Then: dbutils.secrets.put("upsc-bot-secrets", "google-ai-key", "YOUR_KEY")')

if GOOGLE_API_KEY:
    try:
        import subprocess
        subprocess.check_call(["pip", "install", "google-genai", "-q"])
        from google import genai

        client = genai.Client(api_key=GOOGLE_API_KEY)

        # Read today's combined podcast source
        source_content = safe_read(OUTPUT_FILES["combined"])
        if not source_content:
            source_content = combined_doc  # Fallback to in-memory

        # Use Gemini to generate enhanced podcast-style audio script
        print(f"\n   ⏳ Generating enhanced audio script via Gemini...")

        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=f"""You are creating an audio podcast script for UPSC exam preparation.

Convert this into a vivid, engaging 2-host conversation.
Hosts: Arjun (analyst) and Priya (strategist).
Make it sound natural for text-to-speech conversion.
Use short sentences. Add natural pauses marked as [pause].
Emphasize key facts by saying "remember this" or "this is crucial".
Include 3 mnemonics for complex topics.
End with a motivational one-liner.

SOURCE MATERIAL:
{source_content[:10000]}

Generate the enhanced script now."""
        )

        enhanced_script = response.text

        # Save enhanced script
        enhanced_path = f"{PRACTICE_DIR}/podcast_enhanced_{TODAY}.md"
        ok, sz = safe_write(enhanced_path, enhanced_script)
        if ok:
            print(f"   ✅ Enhanced script saved ({sz:,} bytes)")
            print(f"   📁 {enhanced_path}")

        # Preview
        print(f"\n   ENHANCED SCRIPT PREVIEW:")
        print(f"   {'-'*50}")
        print(enhanced_script[:800])
        if len(enhanced_script) > 800:
            print(f"\n   ... [{len(enhanced_script) - 800:,} more chars]")

    except Exception as e:
        print(f"   ❌ Gemini integration failed: {e}")
        import traceback
        traceback.print_exc()

# ──────────────────────────────────────────────────────────────────────
# OPTION B: Manual NotebookLM Workflow (always works)
# ──────────────────────────────────────────────────────────────────────
print(f"\n{'='*60}")
print(f"📖 NotebookLM Manual Workflow (BEST audio quality):")
print(f"{'-'*60}")
print(f"""   1. Go to https://notebooklm.google.com
   2. Create notebook: "UPSC Daily CA {TODAY}"
   3. Upload these files as sources:
      • combined_for_podcast.md (10 KB — today's CA)
      • key_insights.md (3.6 KB — revision card)
      • podcast_transcript.md (14.8 KB — dialogue script)
   4. Click "Audio Overview" → NotebookLM generates podcast
   5. Download the audio + listen in browser

   💡 PRO TIP: Upload your ENTIRE knowledge base (75K chunks)
      to a permanent NotebookLM notebook for deep Q&A!
      NB9 exports chunks as JSONL → split into 50 files → upload all.

   📍 FILES READY AT:
   {PRACTICE_DIR}/
""")

# ──────────────────────────────────────────────────────────────────────
# OPTION C: GitHub Pages — Access from ANYWHERE
# ──────────────────────────────────────────────────────────────────────
print(f"\n🌐 MULTI-PLATFORM ACCESS STRATEGY:")
print(f"{'-'*60}")
print(f"""   Once NB9 pushes to GitHub, your content is accessible from:

   📱 Obsidian (Phone/Mac)
      • Obsidian Git plugin syncs from UPSC_2027 repo
      • Daily_Practice/{TODAY}/ appears in vault
      • Podcast transcript readable as markdown

   🧠 NotebookLM (Best for audio)
      • Import from GitHub: paste combined_for_podcast.md URL
      • Or upload directly from Volume/local
      • Audio Overview = professional 2-host podcast

   💻 Claude Projects (Best for Q&A)
      • Upload knowledge_base_chunks.jsonl as project knowledge
      • Ask any UPSC question with full context

   🔍 ChatGPT (Quick queries)
      • Upload key_insights.md for daily briefing
      • Or full chunks for deep analysis

   🎧 Audio Player (after TTS)
      • MP3 saved at: podcast_{TODAY}.mp3
      • Open in Obsidian, any media player, or phone
""")
print(f"✅ Integration setup complete!")

# COMMAND ----------

# DBTITLE 1,Cell 10: NotebookLM Automated Podcast (notebooklm-py)
# ═══════════════════════════════════════════════════════════════════════════
# CELL 10: NotebookLM — Consolidated Multi-Day Podcast (PRODUCTION)
#
# Merges: Section A-H structure + Working async API
# Auth: Browser cookies from secrets | API: async with
# Source: Consolidates last 3 days of practice materials
# Output: Studio-quality AI podcast (25+ MB WAV)
# ═══════════════════════════════════════════════════════════════════════════

import subprocess, os, json, asyncio
from datetime import date, timedelta, datetime

try:
    subprocess.check_call(["pip", "install", "notebooklm-py", "nest_asyncio", "-q"],
                          stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    from notebooklm import NotebookLMClient
    import nest_asyncio
    nest_asyncio.apply()
except Exception as e:
    print(f"Install error: {e}")

_TODAY = date.today().isoformat()
_BASE = "/Volumes/upsc_catalog/rag/obsidian_ca"
_PRACTICE_DIR = f"{_BASE}/Daily_Practice/{_TODAY}"
os.makedirs(_PRACTICE_DIR, exist_ok=True)
_ARROW = " \u2192 "  # Arrow symbol for display
_DASH = " \u2014 "   # Em-dash for display

def safe_read(path):
    try:
        with open(path, 'r') as f:
            return f.read()
    except:
        return ""

# \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
# PHASE 1: Build Consolidated Source (Section A-H structure)
# \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
print("\U0001f399\ufe0f NotebookLM \u2014 Consolidated Multi-Day Podcast")
print(f"{'='*60}")
print("\n\U0001f4e6 PHASE 1: Building consolidated source...")

# Gather content from last 3 days
days = [(date.today() - timedelta(days=i)).isoformat() for i in range(3)]
days.reverse()

# Section B: Combined CA notes
section_b = ""
for d in days:
    content = safe_read(f"{_BASE}/Daily_Practice/{d}/combined_for_podcast.md")
    if content and len(content) > 100:
        section_b += f"\n### {d}\n\n{content[:8000]}\n"

# Section C: Key insights
section_c = ""
for d in days:
    content = safe_read(f"{_BASE}/Daily_Practice/{d}/key_insights.md")
    if content and len(content) > 100:
        section_c += f"\n### Insights ({d})\n\n{content[:4000]}\n"

# Section D: Deep content (QA, Mains, MCQs)
section_d = ""
for d in days:
    for fname in ["01_Knowledge_QA.md", "05_Mains_Model_Answers.md", "03_Prelims_MCQs.md"]:
        content = safe_read(f"{_BASE}/Daily_Practice/{d}/{fname}")
        if content and len(content) > 100:
            label = fname.replace('.md','').replace('_',' ')
            section_d += f"\n### {label} ({d})\n\n{content[:3000]}\n"

# Section E: Traps from Delta
section_e = ""
try:
    traps = spark.sql(f"""
        SELECT story_title, trap_statement, correct_understanding, trap_type
        FROM upsc_catalog.rag.story_traps
        WHERE date >= '{days[0]}'
        ORDER BY date DESC LIMIT 15
    """).collect()
    for t in traps:
        section_e += f"\n- WRONG: \"{t.trap_statement}\"\n  RIGHT: \"{t.correct_understanding}\" ({t.trap_type})\n"
except:
    section_e = "No traps data available.\n"

# Section F: Weak topics
section_f = ""
try:
    weak = spark.sql("""
        SELECT topic_name, subject, paper, mastery_pct
        FROM upsc_catalog.rag.mastery_tracker
        WHERE mastery_pct < 60 ORDER BY mastery_pct LIMIT 10
    """).collect()
    for w in weak:
        section_f += f"- {w.topic_name} ({w.subject}, {w.paper}) - {w.mastery_pct}% mastery\n"
except:
    section_f = "No mastery data available.\n"

day_range = f"{days[0]} to {days[-1]}"
day_list = ", ".join(days)

consolidated = f"""# UPSC CSE 2027 Podcast Source - {day_range}
## Consolidated for NotebookLM Audio Overview

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M IST')}
**Format:** 2-host podcast (Arjun = analyst, Priya = strategist)
**Audience:** UPSC CSE aspirants preparing for Mains

---

## SECTION A: FOUNDATION (Overview)

This podcast covers {len(days)} days of current affairs ({day_list}).
All stories are analyzed for UPSC relevance across GS Papers I-IV.

---

## SECTION B: CURRENT AFFAIRS NOTES

{section_b if section_b else 'No CA notes available for these dates.'}

---

## SECTION C: KEY INSIGHTS & MEMORY HOOKS

{section_c if section_c else 'No insights available.'}

---

## SECTION D: DEEP DIVE - CONCEPT CONNECTIONS

{section_d if section_d else 'No deep content available.'}

---

## SECTION E: TRAPS YOU MUST KNOW

{section_e}

---

## SECTION F: YOUR WEAK TOPICS (from Mastery Tracker)

{section_f}

---

## SECTION G: PODCAST DISCUSSION GUIDE

**Arjun (Analyst):** Data, facts, timelines, historical context, policy details.
**Priya (Strategist):** Implications, trade-offs, exam angles, decision frameworks.
**Dynamic:** Arjun explains WHAT, Priya challenges with SO WHAT, Together: NOW WHAT.

---

## SECTION H: QUICK MEMORY HOOKS

For each major story, create a mnemonic or analogy.
Connect stories across days to show thematic patterns.
End with: "If you remember nothing else from these 3 days, remember these 5 things..."
"""

if len(consolidated) > 100000:
    consolidated = consolidated[:100000]

out_path = f"{_PRACTICE_DIR}/consolidated_{days[0]}_to_{days[-1]}.md"
with open(out_path, 'w') as f:
    f.write(consolidated)

days_display = _ARROW.join(days)
print(f"   \u2705 Source built: {len(consolidated):,} chars ({len(consolidated)//1024} KB)")
print(f"   \U0001f4c5 Days: {days_display}")
print(f"   \U0001f4c1 {out_path}")

# \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
# PHASE 2: Generate NotebookLM Podcast (async)
# \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
async def run_notebooklm():
    print(f"\n\U0001f3a7 PHASE 2: NotebookLM Podcast Generation")

    home = os.path.expanduser("~")
    SP = os.path.join(home, ".notebooklm", "storage_state.json")
    try:
        sj = dbutils.secrets.get("upsc-bot-secrets", "notebooklm-storage-state")
        os.makedirs(os.path.dirname(SP), exist_ok=True)
        with open(SP, 'w') as f:
            f.write(sj)
        print("   \u2705 Cookies loaded")
    except Exception:
        print("   \u274c No cookies. Run: notebooklm login on Mac")
        return

    async with await NotebookLMClient.from_storage(SP) as client:
        print("   \u2705 Client connected!")

        title = f"UPSC Weekly CA - {day_range}"
        print(f"   \u23f3 Creating: {title}")
        nb = await client.notebooks.create(title=title)
        print(f"   \U0001f4d3 ID: {nb.id}")

        print(f"   \u23f3 Adding source ({len(consolidated):,} chars)...")
        src = await client.sources.add_text(
            notebook_id=nb.id, title=f"UPSC CA {day_range}",
            content=consolidated, wait=True, wait_timeout=180.0)
        print(f"   \u2705 Source: {src.id}")

        print("   \u23f3 Generating Audio Overview...")
        await client.artifacts.generate_audio(
            notebook_id=nb.id,
            source_ids=[src.id],
            language="en",
            instructions="""Create a 15-20 minute UPSC exam preparation podcast covering 3 days of current affairs.

Two hosts:
- Arjun: Senior analyst. Explains facts, numbers, timelines, policy details.
- Priya: Sharp strategist. Challenges with "so what?", focuses on exam relevance, gives mnemonics.

Structure:
1. Opening (1 min): "Good morning aspirants! 3-day current affairs wrap-up."
2. Section B (8 min): Cover ALL major stories. What happened, Why UPSC cares, Which paper.
3. Traps (3 min): Common mistakes from Section E. "Students often think X, but actually Y."
4. Cross-connections (3 min): Link stories across days thematically.
5. Weak topics (2 min): Quick review of Section F topics to focus on.
6. Closing (2 min): "5 things to remember" + motivational sign-off.

Tone: Like two IAS officers mentoring over morning chai. Engaging, with analogies and stories."""
        )
        print("   \U0001f504 Generation started")

        audio_path = f"{_PRACTICE_DIR}/notebooklm_WEEKLY_{_TODAY}.wav"
        print("   \u23f3 Waiting for audio (up to 15 min)...")
        for i in range(90):
            try:
                await client.artifacts.download_audio(
                    notebook_id=nb.id, output_path=audio_path)
                sz = os.path.getsize(audio_path) / 1024 / 1024
                elapsed = (i+1)*10
                print(f"\n   \u2705 PODCAST DOWNLOADED! {sz:.1f} MB ({elapsed}s)")
                print(f"   \U0001f4c1 {audio_path}")

                meta = {"timestamp": datetime.now().isoformat(), "notebook_id": nb.id,
                        "source_chars": len(consolidated), "days": days,
                        "file_mb": round(sz, 1), "generation_seconds": elapsed}
                with open(f"{_PRACTICE_DIR}/notebooklm_metadata.json", 'w') as f:
                    json.dump(meta, f, indent=2)
                return True
            except Exception:
                if i < 89:
                    await asyncio.sleep(10)
                    if (i+1) % 6 == 0:
                        print(f"      Still generating... ({(i+1)*10}s)")
                else:
                    print(f"\n   \u274c Timed out (15 min)")
                    print(f"   Check notebooklm.google.com for notebook: {nb.id}")
                    return False

asyncio.run(run_notebooklm())

# COMMAND ----------



# COMMAND ----------

# DBTITLE 1,Cell 11: Google Cloud TTS (WaveNet) + Multi-Speaker
# ═══════════════════════════════════════════════════════════════════════════
# CELL 11: Google Cloud TTS (WaveNet) — Multi-Speaker Podcast Audio
# Uses $406 GCP credits on project dbx999
# Self-contained: defines all paths locally
# ═══════════════════════════════════════════════════════════════════════════

import re, io, base64
from datetime import date
import requests as _req

# Self-contained path definitions (no dependency on Cell 1 session)
_TODAY = date.today().isoformat()
_BASE = "/Volumes/upsc_catalog/rag/obsidian_ca"
_PRACTICE_DIR = f"{_BASE}/Daily_Practice/{_TODAY}"
_OBSIDIAN_VOL = _BASE

print(f"🔊 Google Cloud TTS — WaveNet Multi-Speaker Audio")
print(f"{'='*60}")

GCP_TTS_KEY = None
try:
    GCP_TTS_KEY = dbutils.secrets.get("upsc-bot-secrets", "gcloud-tts-key")
    print(f"   ✅ GCP TTS API key loaded")
except Exception:
    print(f"   ⚠️  GCP TTS key not set.")

# Use transcript from Cell 4 if available, otherwise try reading from file
_transcript = None
try:
    _transcript = transcript  # From Cell 4
except NameError:
    try:
        with open(f"{_PRACTICE_DIR}/podcast_transcript.md", 'r') as f:
            _transcript = f.read()
        print(f"   📄 Loaded transcript from file ({len(_transcript):,} chars)")
    except:
        pass

if GCP_TTS_KEY and _transcript:
    VOICES = {
        "ARJUN": {"name": "en-IN-Wavenet-B", "gender": "MALE"},
        "PRIYA": {"name": "en-IN-Wavenet-A", "gender": "FEMALE"},
        "NARRATOR": {"name": "en-IN-Wavenet-D", "gender": "MALE"},
    }

    def tts_synthesize(text, voice_name, gender):
        url = f"https://texttospeech.googleapis.com/v1/text:synthesize?key={GCP_TTS_KEY}"
        payload = {
            "input": {"text": text[:5000]},
            "voice": {"languageCode": "en-IN", "name": voice_name, "ssmlGender": gender},
            "audioConfig": {
                "audioEncoding": "MP3", "speakingRate": 1.0,
                "effectsProfileId": ["headphone-class-device"]
            }
        }
        r = _req.post(url, json=payload, timeout=30)
        if r.status_code == 200:
            return base64.b64decode(r.json().get("audioContent", ""))
        else:
            print(f"      TTS err: {r.status_code} {r.text[:80]}")
            return None

    # Parse transcript into speaker turns
    print(f"\n   ⏳ Parsing transcript into speaker turns...")
    turns = []
    current_speaker = "NARRATOR"
    current_text = ""

    for line in _transcript.split("\n"):
        line = line.strip()
        if not line:
            continue
        line = re.sub(r'\*\*(.+?)\*\*', r'\1', line)
        line = re.sub(r'^#{1,3}\s+', '', line)
        line = re.sub(r'---+', '', line)
        line = re.sub(r'\[.*?\]', '', line)

        if line.startswith("ARJUN:"):
            if current_text.strip():
                turns.append((current_speaker, current_text.strip()))
            current_speaker = "ARJUN"
            current_text = line[6:].strip()
        elif line.startswith("PRIYA:"):
            if current_text.strip():
                turns.append((current_speaker, current_text.strip()))
            current_speaker = "PRIYA"
            current_text = line[6:].strip()
        else:
            current_text += " " + line

    if current_text.strip():
        turns.append((current_speaker, current_text.strip()))

    print(f"   Parsed {len(turns)} speaker turns")

    # Generate audio
    print(f"   ⏳ Generating multi-speaker audio (1-2 min)...")
    all_audio = io.BytesIO()
    success_count = 0

    for i, (speaker, text) in enumerate(turns[:50]):
        voice = VOICES.get(speaker, VOICES["NARRATOR"])
        audio_bytes = tts_synthesize(text, voice["name"], voice["gender"])
        if audio_bytes:
            all_audio.write(audio_bytes)
            success_count += 1
        if (i + 1) % 10 == 0:
            print(f"      Turn {i+1}/{min(len(turns), 50)} done...")

    if success_count > 0:
        audio_data = all_audio.getvalue()
        audio_size = len(audio_data)

        # Write directly to Volume paths
        import os
        os.makedirs(_PRACTICE_DIR, exist_ok=True)
        tts_path = f"{_PRACTICE_DIR}/podcast_gcloud_{_TODAY}.mp3"
        with open(tts_path, 'wb') as f:
            f.write(audio_data)

        obsidian_audio = f"{_OBSIDIAN_VOL}/UPSC_2026/01_Current_Affairs/2026/podcast_{_TODAY}.mp3"
        os.makedirs(os.path.dirname(obsidian_audio), exist_ok=True)
        with open(obsidian_audio, 'wb') as f:
            f.write(audio_data)

        est_min = round(audio_size / (16000 * 60 / 8), 1)
        print(f"\n   ✅ Multi-speaker podcast generated!")
        print(f"   📁 {tts_path}")
        print(f"   📊 {audio_size/1024/1024:.1f} MB | {success_count} turns | ~{est_min} min")
        print(f"   🌐 Arjun: en-IN-Wavenet-B | Priya: en-IN-Wavenet-A")
        print(f"   📓 Obsidian: {obsidian_audio}")
    else:
        print(f"   ❌ No audio generated.")

    char_count = sum(len(t[1]) for t in turns[:50])
    cost = (char_count * 16) / 1000000
    print(f"\n{'='*60}")
    print(f"   💰 Chars: {char_count:,} | Cost: ${cost:.4f} | Credits: ~$406")
elif not _transcript:
    print("   ⚠️  No transcript. Run Cell 4 first.")
else:
    print("   ⚠️  No TTS API key.")